appname = sga_calendario_mid
httpport = ${SGA_CALENDARIO_MID_HTTP_PORT}
runmode = ${SGA_CALENDARIO_MID_RUNMODE||prod}
parameterStore = ${PARAMETER_STORE}
autorender = false
copyrequestbody = true
EnableDocs = true


CoreService = ${CORE_SERVICE}
DocumentosService= ${DOCUMENTO_SERVICE}
EventoService = ${EVENTOS_SERVICE}
OikosService = ${OIKOS_SERVICE}
ParametroService= ${PARAMETRO_SERVICE}
ProyectoAcademicoService= ${PROYECTO_ACADEMICO_SERVICE}
TercerosService= ${TERCEROS_SERVICE}