appname = sga_calendario_mid
httpport = ${SGA_CALENDARIO_MID_HTTP_PORT}
runmode = ${SGA_CALENDARIO_MID_RUNMODE||prod}
parameterStore = ${PARAMETER_STORE}
autorender = false
copyrequestbody = true
EnableDocs = true


CoreService = ${CORE_SERVICE}
DocumentosService= ${DOCUMENTO_SERVICE}
EventoService = ${EVENTOS_SERVICE}
OikosService = ${OIKOS_SERVICE}
ParametroService= ${PARAMETRO_SERVICE}
ProyectoAcademicoService= ${PROYECTO_ACADEMICO_SERVICE}
TercerosService= ${TERCEROS_SERVICE}
ConfiguracionService= ${CONFIGURACION_SERVICE}
Wso2Service= ${WSO2_SERVICE}
Wso2AcademicaService= ${WSO2_ACADEMICA_SERVICE}
Wso2HomologacionService= ${WSO2_HOMOLOGACION_SERVICE}
